const pool = require("../config/db");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");


// Create Contact
const createContact = async (req, res) => {

    let newUploadedPath = null;
    try {

        console.log("===== CREATE CONTACT CALLED =====");
        console.log("BODY:", req.body);
        console.log("FILE:", req.file);

        const { name, phone, email, address } = req.body;

        // ================================
        // VALIDATION
        // ================================

        if (!name || !phone) {

            if (req.file) {    
                if (req.file && fs.existsSync(req.file.path))
                    fs.unlinkSync(req.file.path);}

            return res.status(400).json({
                message: "Name and phone are required"
            });
        }

        // ================================
        // LOGGED-IN USER ID
        // ================================

        const userId = req.user.userId;

        // ================================
        // TEMPORARY IMAGE + DUPLICATE CHECK
        // ================================

        let imagePath = null;
        let imageHash = null;

        if (req.file) {

            imagePath = req.file.filename;

            // Compute hash of the actual image content
            const fileBuffer = fs.readFileSync(req.file.path);
            imageHash = crypto.createHash("sha256").update(fileBuffer).digest("hex");

            // Check if this exact photo is already used by ANY contact (global check)
            const [duplicateImage] = await pool.query(
                "SELECT id FROM contacts WHERE image_hash = ?",
                [imageHash]
            );

            if (duplicateImage.length > 0) {

                if (fs.existsSync(req.file.path)) {
                    fs.unlinkSync(req.file.path);
                }

                return res.status(409).json({
                    message: "This photo is already used for another contact."
                });
            }
        }

        // ================================
        // INSERT CONTACT
        // ================================

        const [result] = await pool.query(
            `INSERT INTO contacts
            (user_id, name, phone, email, address, image_path, image_hash)
            VALUES (?, ?, ?, ?, ?, ?, ?)`,
            [
                userId,
                name,
                phone,
                email,
                address,
                imagePath,
                imageHash
            ]
        );

        // ================================
        // CONTACT ID GENERATED BY MYSQL
        // ================================

        const contactId = result.insertId;

        console.log("USER ID:", userId);
        console.log("CONTACT ID:", contactId);

        // ================================
        // RENAME IMAGE
        // ================================

        if (req.file) {

            const oldPath = req.file.path;

            const extension = path.extname(
                req.file.originalname
            );

            const finalFileName =
                `${userId}-${contactId}-${path.basename(
                    req.file.originalname,
                    extension
                )}${extension}`;

            newUploadedPath = path.join(
                path.dirname(oldPath),
                finalFileName
            );

            fs.renameSync(
                oldPath,
                newUploadedPath
            );

            // ================================
            // UPDATE IMAGE PATH IN DATABASE
            // ================================

            imagePath = `uploads/${finalFileName}`;

            await pool.query(
                `UPDATE contacts
                 SET image_path = ?
                 WHERE id = ? AND user_id = ?`,
                [
                    imagePath,
                    contactId,
                    userId
                ]
            );

            console.log(
                "FINAL IMAGE NAME:",
                finalFileName
            );
        }

        // ================================
        // RESPONSE
        // ================================

        res.status(201).json({
            message: "Contact created successfully",
            contactId: contactId,
            imagePath: imagePath
        });

    }  catch (error) {
    console.error("Create Contact Error:", error);

    // clean up whichever file actually exists on disk
    const fileToDelete = newUploadedPath || (req.file && req.file.path);
    if (fileToDelete) {
        try {
            if (fs.existsSync(fileToDelete)) fs.unlinkSync(fileToDelete);
        } catch (deleteError) {
            console.error("Image cleanup error:", deleteError);
        }
    }

    // duplicate key (email / image_path unique constraint)
    if (error.code === 'ER_DUP_ENTRY') {
        let field = 'value';
        if (error.sqlMessage.includes('email')) field = 'email';
        else if (error.sqlMessage.includes('image_path')) field = 'image';

        return res.status(409).json({
            message: `This ${field} is already in use.`
        });
    }

    res.status(500).json({ message: "Server error" });
}
};
// =====================================================
// GET ALL CONTACTS
// =====================================================

const getContacts = async (req, res) => {
    try {

        const userId = req.user.userId;

        const [contacts] = await pool.query(
            `SELECT
                id,
                user_id,
                name,
                phone,
                email,
                address,
                image_path
             FROM contacts
             WHERE user_id = ?
             ORDER BY id DESC`,
            [userId]
        );

        res.status(200).json({
            contacts: contacts
        });

    } catch (error) {

        console.error(
            "Get Contacts Error:",
            error
        );

        res.status(500).json({
            message: "Server error"
        });
    }
};
// =====================================================
// GET CONTACT BY ID
// =====================================================

const getContactById = async (req, res) => {
    try {

        const contactId = req.params.id;
        const userId = req.user.userId;

        const [contacts] = await pool.query(
            `SELECT
                id,
                user_id,
                name,
                phone,
                email,
                address,
                image_path
             FROM contacts
             WHERE id = ?
             AND user_id = ?`,
            [
                contactId,
                userId
            ]
        );

        if (contacts.length === 0) {

            return res.status(404).json({
                message: "Contact not found"
            });
        }

        res.status(200).json({
            contact: contacts[0]
        });

    } catch (error) {

        console.error(
            "Get Contact By ID Error:",
            error
        );

        res.status(500).json({
            message: "Server error"
        });
    }
};
// =====================================================
// UPDATE CONTACT
// =====================================================

const updateContact = async (req, res) => {
      let newUploadedPath = null;
    try {
      
        const { name, phone, email, address } = req.body;

        const contactId = req.params.id;

        const userId = req.user.userId;

        // Find existing contact
        const [existingContact] = await pool.query(
            `SELECT *
             FROM contacts
             WHERE id = ?
             AND user_id = ?`,
            [
                contactId,
                userId
            ]
        );

        if (existingContact.length === 0) {

         
            if (req.file) {

                try {

                    if (fs.existsSync(req.file.path)) {
                        fs.unlinkSync(req.file.path);
                    }

                } catch (error) {
                    console.error(
                        "Image delete error:",
                        error
                    );
                }
            }

            return res.status(404).json({
                message: "Contact not found"
            });
        }

        // ============================================
        // UPDATE WITHOUT NEW IMAGE
        // ============================================

        if (!req.file) {

            await pool.query(
                `UPDATE contacts
                 SET
                    name = ?,
                    phone = ?,
                    email = ?,
                    address = ?
                 WHERE id = ?
                 AND user_id = ?`,
                [
                    name,
                    phone,
                    email,
                    address,
                    contactId,
                    userId
                ]
            );

            return res.status(200).json({
                message: "Contact updated successfully"
            });
        }

        // ============================================
        // NEW IMAGE SELECTED + DUPLICATE CHECK
        // ============================================

        const fileBuffer = fs.readFileSync(req.file.path);
        const imageHash = crypto.createHash("sha256").update(fileBuffer).digest("hex");

        // Check if this exact photo is used by a DIFFERENT contact (global check)
        const [duplicateImage] = await pool.query(
            "SELECT id FROM contacts WHERE image_hash = ? AND id != ?",
            [imageHash, contactId]
        );

        if (duplicateImage.length > 0) {

            if (fs.existsSync(req.file.path)) {
                fs.unlinkSync(req.file.path);
            }

            return res.status(409).json({
                message: "This photo is already used for another contact."
            });
        }

        const oldImagePath =
            existingContact[0].image_path;

        const extension = path.extname(
            req.file.originalname
        );

        const originalNameWithoutExtension =
            path.basename(
                req.file.originalname,
                extension
            );

       

        const finalFileName =
            `${userId}-${contactId}-${originalNameWithoutExtension}${extension}`;

        const oldUploadedPath =
            req.file.path;


        newUploadedPath =
            path.join(
                path.dirname(oldUploadedPath),
                finalFileName
            );

        // Rename new uploaded image
        fs.renameSync(
            oldUploadedPath,
            newUploadedPath
        );

        const newImagePath =
            `uploads/${finalFileName}`;

        // ============================================
        // UPDATE CONTACT + IMAGE
        // ============================================

        await pool.query(
            `UPDATE contacts
             SET
                name = ?,
                phone = ?,
                email = ?,
                address = ?,
                image_path = ?,
                image_hash = ?
             WHERE id = ?
             AND user_id = ?`,
            [
                name,
                phone,
                email,
                address,
                newImagePath,
                imageHash,
                contactId,
                userId
            ]
        );

        // ============================================
        // DELETE OLD IMAGE
        // ============================================

        if (oldImagePath) {

            const oldFullPath =
                path.join(
                    __dirname,
                    "..",
                    oldImagePath
                );

            try {

                if (fs.existsSync(oldFullPath)) {

                    fs.unlinkSync(
                        oldFullPath
                    );
                }

            } catch (deleteError) {

                console.error(
                    "Old image delete error:",
                    deleteError
                );
            }
        }

        res.status(200).json({
            message: "Contact updated successfully",
            imagePath: newImagePath
        });

    } catch (error) {

    console.error(
        "Update Contact Error:",
        error
    );

    // Delete newly renamed image if something failed
    if (newUploadedPath) {

        try {

            if (fs.existsSync(newUploadedPath)) {
                fs.unlinkSync(newUploadedPath);
            }

        } catch (deleteError) {

            console.error(
                "Image cleanup error:",
                deleteError
            );
        }
    }

    res.status(500).json({
        message: "Server error"
    });
}
};
// =====================================================
// DELETE CONTACT
// =====================================================

const deleteContact = async (req, res) => {
    try {

        const contactId = req.params.id;

        const userId = req.user.userId;

        // Get contact first so we know
        // which image belongs to it
        const [contacts] = await pool.query(
            `SELECT image_path
             FROM contacts
             WHERE id = ?
             AND user_id = ?`,
            [
                contactId,
                userId
            ]
        );

        if (contacts.length === 0) {

            return res.status(404).json({
                message: "Contact not found"
            });
        }

        const imagePath =
            contacts[0].image_path;

        // ============================================
        // DELETE DATABASE RECORD
        // ============================================

        await pool.query(
            `DELETE FROM contacts
             WHERE id = ?
             AND user_id = ?`,
            [
                contactId,
                userId
            ]
        );

        // ============================================
        // DELETE IMAGE FILE
        // ============================================

        if (imagePath) {

            const fullImagePath =
                path.join(
                    __dirname,
                    "..",
                    imagePath
                );

            try {

                if (fs.existsSync(fullImagePath)) {

                    fs.unlinkSync(
                        fullImagePath
                    );
                }

            } catch (deleteError) {

                console.error(
                    "Image delete error:",
                    deleteError
                );
            }
        }

        res.status(200).json({
            message: "Contact deleted successfully"
        });

    } catch (error) {

        console.error(
            "Delete Contact Error:",
            error
        );

        res.status(500).json({
            message: "Server error"
        });
    }
};
module.exports = { 
    createContact, 
    getContacts, 
    getContactById,
    updateContact,
    deleteContact 
};